version: "3.7"

x-tifa-common:
  &tifa-common
  image: tifa:local
  volumes:
    - .:/opt/tifa
  environment:
    &tifa-common-env
    SECRET_KEY: "ZF8dr8z@L*asd3oR?R/pe1}|l12enem(ppFV=U<!F@lF-k9wE"
    SETTING_PATH: "/opt/tifa/settings_docker.py"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./compose/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./.volume/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  elasticsearch:
    image: elasticsearch:local
    ports:
      - '9200:9200'
      - '9100:9100'

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  tifa-web:
    <<: *tifa-common
    command: [ "tifa-cli", "web", "start" ]
    ports:
      - "8000:8000"

  tifa-toolbox:
    <<: *tifa-common
    command: [ "tifa-cli" ]

  tifa-worker:
    <<: *tifa-common
    command: [ "tifa-cli", "worker", "start" ]

  tifa-beat:
    <<: *tifa-common
    command: [ "tifa-cli", "worker", "beat" ]

  tifa-flower:
    <<: *tifa-common
    command: [ "tifa-cli", "worker", "monitor" ]

volumes:
  postgres_data_dev: { }
  postgres_backup_dev: { }
