"""empty message

Revision ID: 062cfe148a4f
Revises: 423f73fe755f
Create Date: 2021-08-24 13:44:07.795638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '062cfe148a4f'
down_revision = '423f73fe755f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_collection_translation')
    op.drop_table('product_category_translation')
    op.drop_index('ix_product_category_tree_id', table_name='product_category')
    op.drop_column('product_category', 'level')
    op.drop_column('product_category', 'tree_id')
    op.drop_column('product_category', 'lft')
    op.drop_column('product_category', 'rght')
    op.drop_column('user', 'jwt_token_key')
    op.drop_column('user', 'language_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_code', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('jwt_token_key', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('product_category', sa.Column('rght', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_category', sa.Column('lft', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_category', sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_category', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_product_category_tree_id', 'product_category', ['tree_id'], unique=False)
    op.create_table('product_category_translation',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seo_title', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], name='product_category_translation_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_category_translation_pkey'),
    sa.UniqueConstraint('language_code', 'category_id', name='product_category_translation_language_code_category_id_key')
    )
    op.create_table('product_collection_translation',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seo_title', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], name='product_collection_translation_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_collection_translation_pkey'),
    sa.UniqueConstraint('language_code', 'collection_id', name='product_collection_translation_language_code_collection_id_key')
    )
    # ### end Alembic commands ###
