"""empty message

Revision ID: 19d5fbd43af3
Revises: 
Create Date: 2021-07-26 20:58:49.610386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19d5fbd43af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('street_address_1', sa.String(length=256), nullable=False),
    sa.Column('street_address_2', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('country_area', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=128), nullable=False),
    sa.Column('city_area', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('about_app', sa.Text(), nullable=True),
    sa.Column('app_url', sa.String(length=200), nullable=True),
    sa.Column('configuration_url', sa.String(length=200), nullable=True),
    sa.Column('data_privacy', sa.Text(), nullable=True),
    sa.Column('data_privacy_url', sa.String(length=200), nullable=True),
    sa.Column('homepage_url', sa.String(length=200), nullable=True),
    sa.Column('identifier', sa.String(length=256), nullable=True),
    sa.Column('support_url', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_metadata_private'), 'app', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_app_metadata_public'), 'app', ['metadata_public'], unique=False)
    op.create_table('app_installation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=60), nullable=False),
    sa.Column('manifest_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_type', sa.String(length=50), nullable=False),
    sa.Column('available_in_grid', sa.Boolean(), nullable=False),
    sa.Column('visible_in_storefront', sa.Boolean(), nullable=False),
    sa.Column('filterable_in_dashboard', sa.Boolean(), nullable=False),
    sa.Column('filterable_in_storefront', sa.Boolean(), nullable=False),
    sa.Column('value_required', sa.Boolean(), nullable=False),
    sa.Column('storefront_search_position', sa.Integer(), nullable=False),
    sa.Column('is_variant_only', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_attribute_metadata_private'), 'attribute', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_attribute_metadata_public'), 'attribute', ['metadata_public'], unique=False)
    op.create_table('channel',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('discount_sale',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_voucher',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('discount_value_type', sa.String(length=10), nullable=False),
    sa.Column('apply_once_per_order', sa.Boolean(), nullable=False),
    sa.Column('countries', sa.String(length=749), nullable=False),
    sa.Column('min_checkout_items_quantity', sa.Integer(), nullable=True),
    sa.Column('apply_once_per_customer', sa.Boolean(), nullable=False),
    sa.Column('only_for_staff', sa.Boolean(), nullable=False),
    sa.CheckConstraint('min_checkout_items_quantity >= 0'),
    sa.CheckConstraint('usage_limit >= 0'),
    sa.CheckConstraint('used >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('django_prices_openexchangerates_conversionrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('to_currency')
    )
    op.create_table('django_prices_vatlayer_ratetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('types', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_prices_vatlayer_vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_django_prices_vatlayer_vat_country_code'), 'django_prices_vatlayer_vat', ['country_code'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_menu_metadata_private'), 'menu', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_menu_metadata_public'), 'menu', ['metadata_public'], unique=False)
    op.create_table('page_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_page_type_metadata_private'), 'page_type', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_page_type_metadata_public'), 'page_type', ['metadata_public'], unique=False)
    op.create_index('page_type_name_slug', 'page_type', ['name', 'slug'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rght', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('background_image', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('background_image_alt', sa.String(length=128), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('level >= 0'),
    sa.CheckConstraint('lft >= 0'),
    sa.CheckConstraint('rght >= 0'),
    sa.CheckConstraint('tree_id >= 0'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_category_metadata_private'), 'product_category', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_category_metadata_public'), 'product_category', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_product_category_tree_id'), 'product_category', ['tree_id'], unique=False)
    op.create_table('product_collection',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('background_image', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('background_image_alt', sa.String(length=128), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_collection_metadata_private'), 'product_collection', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_collection_metadata_public'), 'product_collection', ['metadata_public'], unique=False)
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('is_shipping_required', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(precision=53), nullable=False),
    sa.Column('is_digital', sa.Boolean(), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_type_metadata_private'), 'product_type', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_type_metadata_public'), 'product_type', ['metadata_public'], unique=False)
    op.create_table('shipping_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('countries', sa.String(length=749), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_zone_metadata_private'), 'shipping_zone', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_shipping_zone_metadata_public'), 'shipping_zone', ['metadata_public'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_installation_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_installation_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_installation_id'], ['app_installation.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_installation_id', 'permission_id')
    )
    op.create_index(op.f('ix_app_installation_permissions_app_installation_id'), 'app_installation_permissions', ['app_installation_id'], unique=False)
    op.create_table('app_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'permission_id')
    )
    op.create_table('app_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('auth_token', sa.String(length=30), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_table('attribute_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('page_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['page_type_id'], ['page_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'page_type_id')
    )
    op.create_index(op.f('ix_attribute_page_sort_order'), 'attribute_page', ['sort_order'], unique=False)
    op.create_table('attribute_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'product_type_id')
    )
    op.create_index(op.f('ix_attribute_product_sort_order'), 'attribute_product', ['sort_order'], unique=False)
    op.create_table('attribute_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'attribute_id')
    )
    op.create_index(op.f('ix_attribute_translation_attribute_id'), 'attribute_translation', ['attribute_id'], unique=False)
    op.create_table('attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=200), nullable=True),
    sa.Column('rich_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'attribute_id')
    )
    op.create_index('idx_attribute_value_name_slug', 'attribute_value', ['name', 'slug'], unique=False)
    op.create_index(op.f('ix_attribute_value_slug'), 'attribute_value', ['slug'], unique=False)
    op.create_index(op.f('ix_attribute_value_sort_order'), 'attribute_value', ['sort_order'], unique=False)
    op.create_table('attribute_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'product_type_id')
    )
    op.create_index(op.f('ix_attribute_variant_sort_order'), 'attribute_variant', ['sort_order'], unique=False)
    op.create_table('discount_sale_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['discount_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'category_id')
    )
    op.create_table('discount_sale_channel_listing',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['discount_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'channel_id')
    )
    op.create_index(op.f('ix_discount_sale_channel_listing_channel_id'), 'discount_sale_channel_listing', ['channel_id'], unique=False)
    op.create_index(op.f('ix_discount_sale_channel_listing_sale_id'), 'discount_sale_channel_listing', ['sale_id'], unique=False)
    op.create_table('discount_sale_collection',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['discount_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'collection_id')
    )
    op.create_table('discount_sale_translation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['discount_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'sale_id')
    )
    op.create_index(op.f('ix_discount_sale_translation_sale_id'), 'discount_sale_translation', ['sale_id'], unique=False)
    op.create_table('discount_voucher_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'category_id')
    )
    op.create_table('discount_voucher_channel_listing',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_spent_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'channel_id')
    )
    op.create_table('discount_voucher_collection',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'collection_id')
    )
    op.create_table('discount_voucher_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(length=254), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'customer_email')
    )
    op.create_table('discount_voucher_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'voucher_id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_type_id'], ['page_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_page_metadata_private'), 'page', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_page_metadata_public'), 'page', ['metadata_public'], unique=False)
    op.create_index('page_title_slug', 'page', ['title', 'slug'], unique=False)
    op.create_table('plugin_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'channel_id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('charge_taxes', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(precision=53), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('default_variant_id', sa.Integer(), nullable=True),
    sa.Column('description_plaintext', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('rating', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['default_variant_id'], ['product_variant.id'], name='fk_product_default_variant_id', use_alter=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('default_variant_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_metadata_private'), 'product', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_metadata_public'), 'product', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_product_search_vector'), 'product', ['search_vector'], unique=False)
    op.create_table('product_category_translation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'category_id')
    )
    op.create_table('product_collection_channel_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'channel_id')
    )
    op.create_table('product_collection_translation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'collection_id')
    )
    op.create_table('shipping_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('maximum_order_weight', sa.Float(precision=53), nullable=True),
    sa.Column('minimum_order_weight', sa.Float(precision=53), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('shipping_zone_id', sa.Integer(), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maximum_delivery_days', sa.Integer(), nullable=True),
    sa.Column('minimum_delivery_days', sa.Integer(), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('maximum_delivery_days >= 0'),
    sa.CheckConstraint('minimum_delivery_days >= 0'),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_method_metadata_private'), 'shipping_method', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_shipping_method_metadata_public'), 'shipping_method', ['metadata_public'], unique=False)
    op.create_table('shipping_zone_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_zone_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipping_zone_id', 'channel_id')
    )
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('bottom_menu_id', sa.Integer(), nullable=True),
    sa.Column('top_menu_id', sa.Integer(), nullable=True),
    sa.Column('display_gross_prices', sa.Boolean(), nullable=False),
    sa.Column('include_taxes_in_prices', sa.Boolean(), nullable=False),
    sa.Column('charge_taxes_on_shipping', sa.Boolean(), nullable=False),
    sa.Column('track_inventory_by_default', sa.Boolean(), nullable=False),
    sa.Column('default_weight_unit', sa.String(length=30), nullable=False),
    sa.Column('automatic_fulfillment_digital_products', sa.Boolean(), nullable=False),
    sa.Column('default_digital_max_downloads', sa.Integer(), nullable=True),
    sa.Column('default_digital_url_valid_days', sa.Integer(), nullable=True),
    sa.Column('company_address_id', sa.Integer(), nullable=True),
    sa.Column('default_mail_sender_address', sa.String(length=254), nullable=True),
    sa.Column('default_mail_sender_name', sa.String(length=78), nullable=False),
    sa.Column('customer_set_password_url', sa.String(length=255), nullable=True),
    sa.Column('automatically_confirm_all_new_orders', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bottom_menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['company_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['top_menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_setting_bottom_menu_id'), 'site_setting', ['bottom_menu_id'], unique=False)
    op.create_index(op.f('ix_site_setting_top_menu_id'), 'site_setting', ['top_menu_id'], unique=False)
    op.create_table('staff_notification_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('staff_email', sa.String(length=254), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_email'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('default_billing_address_id', sa.Integer(), nullable=True),
    sa.Column('default_shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jwt_token_key', sa.String(length=12), nullable=False),
    sa.Column('language_code', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['default_billing_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['default_shipping_address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('account_username_email', 'user', ['email', 'first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_user_metadata_private'), 'user', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_user_metadata_public'), 'user', ['metadata_public'], unique=False)
    op.create_table('warehouse',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_warehouse_metadata_private'), 'warehouse', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_warehouse_metadata_public'), 'warehouse', ['metadata_public'], unique=False)
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_page_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['attribute_page.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['attribute_product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'assignment_id')
    )
    op.create_table('attribute_value_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('rich_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'attribute_value_id')
    )
    op.create_table('checkout',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_change', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('discount_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('voucher_code', sa.String(length=12), nullable=True),
    sa.Column('translated_discount_name', sa.String(length=255), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('redirect_url', sa.String(length=200), nullable=True),
    sa.Column('tracking_code', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['billing_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_metadata_private'), 'checkout', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_checkout_metadata_public'), 'checkout', ['metadata_public'], unique=False)
    op.create_table('collection_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'product_id')
    )
    op.create_index(op.f('ix_collection_product_sort_order'), 'collection_product', ['sort_order'], unique=False)
    op.create_table('csv_export_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content_file', sa.String(length=100), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_export_file_app_id'), 'csv_export_file', ['app_id'], unique=False)
    op.create_table('customer_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_note_date'), 'customer_note', ['date'], unique=False)
    op.create_table('discount_sale_product',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['discount_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'product_id')
    )
    op.create_table('discount_voucher_product',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'product_id')
    )
    op.create_index(op.f('ix_discount_voucher_product_product_id'), 'discount_voucher_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_discount_voucher_product_voucher_id'), 'discount_voucher_product', ['voucher_id'], unique=False)
    op.create_table('gift_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_used_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('initial_balance_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_balance_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rght', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('level >= 0'),
    sa.CheckConstraint('lft >= 0'),
    sa.CheckConstraint('rght >= 0'),
    sa.CheckConstraint('tree_id >= 0'),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collection.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_metadata_private'), 'menu_item', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_menu_item_metadata_public'), 'menu_item', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_menu_item_sort_order'), 'menu_item', ['sort_order'], unique=False)
    op.create_index(op.f('ix_menu_item_tree_id'), 'menu_item', ['tree_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('tracking_client_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(length=35), nullable=False),
    sa.Column('shipping_price_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('shipping_price_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('shipping_method_name', sa.String(length=255), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('display_gross_prices', sa.Boolean(), nullable=False),
    sa.Column('customer_note', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(precision=53), nullable=False),
    sa.Column('checkout_token', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('redirect_url', sa.String(length=200), nullable=True),
    sa.Column('shipping_tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('undiscounted_total_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('undiscounted_total_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_paid_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['discount_voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_order_metadata_private'), 'order', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_order_metadata_public'), 'order', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_order_user_email'), 'order', ['user_email'], unique=False)
    op.create_table('page_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'page_id')
    )
    op.create_table('product_channel_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discounted_price_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('visible_in_listings', sa.Boolean(), nullable=False),
    sa.Column('available_for_purchase', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'channel_id')
    )
    op.create_index(op.f('ix_product_channel_listing_publication_date'), 'product_channel_listing', ['publication_date'], unique=False)
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('ppoi', sa.String(length=20), nullable=False),
    sa.Column('alt', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('external_url', sa.String(length=256), nullable=True),
    sa.Column('oembed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_media_sort_order'), 'product_media', ['sort_order'], unique=False)
    op.create_table('product_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'product_id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(precision=53), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_variant_metadata_private'), 'product_variant', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_variant_metadata_public'), 'product_variant', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_product_variant_sort_order'), 'product_variant', ['sort_order'], unique=False)
    op.create_table('shipping_method_channel_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum_order_price_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('maximum_order_price_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipping_method_id', 'channel_id')
    )
    op.create_table('shipping_method_excluded_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipping_method_id', 'product_id')
    )
    op.create_table('shipping_method_postal_code_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=32), nullable=False),
    sa.Column('end', sa.String(length=32), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('inclusion_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipping_method_id', 'start', 'end')
    )
    op.create_table('shipping_method_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'shipping_method_id')
    )
    op.create_table('site_setting_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('header_text', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('site_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_settings_id'], ['site_setting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'site_settings_id')
    )
    op.create_table('user_address_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address_id')
    )
    op.create_table('warehouse_shipping_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', postgresql.UUID(), nullable=False),
    sa.Column('shipping_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zone.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'shipping_zone_id')
    )
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_event_type'), 'webhook_event', ['event_type'], unique=False)
    op.create_table('wishlist',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', postgresql.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assigned_page_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assigned_page_attribute.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['attribute_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_id', 'assignment_id')
    )
    op.create_index(op.f('ix_assigned_page_attribute_value_sort_order'), 'assigned_page_attribute_value', ['sort_order'], unique=False)
    op.create_table('assigned_product_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assigned_product_attribute.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['attribute_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_id', 'assignment_id')
    )
    op.create_index(op.f('ix_assigned_product_attribute_value_sort_order'), 'assigned_product_attribute_value', ['sort_order'], unique=False)
    op.create_table('assigned_variant_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['attribute_variant.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'assignment_id')
    )
    op.create_table('checkout_gift_card',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_id', postgresql.UUID(), nullable=False),
    sa.Column('gift_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_id', 'gift_card_id')
    )
    op.create_table('checkout_line',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('checkout_id', postgresql.UUID(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_export_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('export_file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['export_file_id'], ['csv_export_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('invoice_file', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_metadata_private'), 'invoice', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_invoice_metadata_public'), 'invoice', ['metadata_public'], unique=False)
    op.create_table('menu_item_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'menu_item_id')
    )
    op.create_index(op.f('ix_menu_item_translation_menu_item_id'), 'menu_item_translation', ['menu_item_id'], unique=False)
    op.create_table('order_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('amount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('translated_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('discount_or_name_d16858_gin', 'order_discount', ['name', 'translated_name'], unique=False)
    op.create_table('order_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_event_app_id'), 'order_event', ['app_id'], unique=False)
    op.create_table('order_fulfillment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_refund_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_refund_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.CheckConstraint('fulfillment_order >= 0'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_fulfillment_metadata_private'), 'order_fulfillment', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_order_fulfillment_metadata_public'), 'order_fulfillment', ['metadata_public'], unique=False)
    op.create_index(op.f('ix_order_fulfillment_order_id'), 'order_fulfillment', ['order_id'], unique=False)
    op.create_table('order_gift_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('gift_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_card.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'gift_card_id')
    )
    op.create_table('order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=386), nullable=False),
    sa.Column('product_sku', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_shipping_required', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('translated_product_name', sa.String(length=386), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('translated_variant_name', sa.String(length=255), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('total_price_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_price_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_discount_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_discount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_discount_reason', sa.Text(), nullable=True),
    sa.Column('unit_discount_type', sa.String(length=10), nullable=False),
    sa.Column('undiscounted_total_price_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('undiscounted_total_price_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('undiscounted_unit_price_gross_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('undiscounted_unit_price_net_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('charge_status', sa.String(length=20), nullable=False),
    sa.Column('billing_first_name', sa.String(length=256), nullable=False),
    sa.Column('billing_last_name', sa.String(length=256), nullable=False),
    sa.Column('billing_company_name', sa.String(length=256), nullable=False),
    sa.Column('billing_address_1', sa.String(length=256), nullable=False),
    sa.Column('billing_address_2', sa.String(length=256), nullable=False),
    sa.Column('billing_city', sa.String(length=256), nullable=False),
    sa.Column('billing_city_area', sa.String(length=128), nullable=False),
    sa.Column('billing_postal_code', sa.String(length=256), nullable=False),
    sa.Column('billing_country_code', sa.String(length=2), nullable=False),
    sa.Column('billing_country_area', sa.String(length=256), nullable=False),
    sa.Column('billing_email', sa.String(length=254), nullable=False),
    sa.Column('customer_ip_address', postgresql.INET(), nullable=True),
    sa.Column('cc_brand', sa.String(length=40), nullable=False),
    sa.Column('cc_exp_month', sa.Integer(), nullable=True),
    sa.Column('cc_exp_year', sa.Integer(), nullable=True),
    sa.Column('cc_first_digits', sa.String(length=6), nullable=False),
    sa.Column('cc_last_digits', sa.String(length=4), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('captured_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('checkout_id', postgresql.UUID(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('to_confirm', sa.Boolean(), nullable=False),
    sa.Column('payment_method_type', sa.String(length=256), nullable=False),
    sa.Column('return_url', sa.String(length=200), nullable=True),
    sa.Column('psp_reference', sa.String(length=512), nullable=True),
    sa.CheckConstraint('cc_exp_month >= 0'),
    sa.CheckConstraint('cc_exp_year >= 0'),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_psp_reference'), 'payment', ['psp_reference'], unique=False)
    op.create_index('payment_pay_order_i_f22aa2_gin', 'payment', ['order_id', 'is_active', 'charge_status'], unique=False)
    op.create_table('product_digital_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_default_settings', sa.Boolean(), nullable=False),
    sa.Column('automatic_fulfillment', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('content_file', sa.String(length=100), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('url_valid_days', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('metadata_public', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_private', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_variant_id')
    )
    op.create_index(op.f('ix_product_digital_content_metadata_private'), 'product_digital_content', ['metadata_private'], unique=False)
    op.create_index(op.f('ix_product_digital_content_metadata_public'), 'product_digital_content', ['metadata_public'], unique=False)
    op.create_table('product_variant_channel_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('cost_price_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'channel_id')
    )
    op.create_table('product_variant_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['product_media.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'media_id')
    )
    op.create_table('product_variant_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'product_variant_id')
    )
    op.create_table('warehouse_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', postgresql.UUID(), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_variant_id')
    )
    op.create_table('wishlist_item',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'product_id')
    )
    op.create_table('assigned_variant_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assigned_variant_attribute.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['attribute_value.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_id', 'assignment_id')
    )
    op.create_index(op.f('ix_assigned_variant_attribute_value_sort_order'), 'assigned_variant_attribute_value', ['sort_order'], unique=False)
    op.create_table('invoice_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_fulfillment_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('fulfillment_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['order_fulfillment.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['warehouse_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=25), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=256), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('action_required_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('already_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_digital_content_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('download_num', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['product_digital_content.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['order_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_product_digital_content_url_content_id'), 'product_digital_content_url', ['content_id'], unique=False)
    op.create_table('warehouse_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_allocated >= 0'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['warehouse_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_line_id', 'stock_id')
    )
    op.create_table('wishlist_item_variant',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_item_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['wishlist_item_id'], ['wishlist_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_item_id', 'product_variant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_item_variant')
    op.drop_table('warehouse_allocation')
    op.drop_index(op.f('ix_product_digital_content_url_content_id'), table_name='product_digital_content_url')
    op.drop_table('product_digital_content_url')
    op.drop_table('payment_transaction')
    op.drop_table('order_fulfillment_line')
    op.drop_table('invoice_event')
    op.drop_index(op.f('ix_assigned_variant_attribute_value_sort_order'), table_name='assigned_variant_attribute_value')
    op.drop_table('assigned_variant_attribute_value')
    op.drop_table('wishlist_item')
    op.drop_table('warehouse_stock')
    op.drop_table('product_variant_translation')
    op.drop_table('product_variant_media')
    op.drop_table('product_variant_channel_listing')
    op.drop_index(op.f('ix_product_digital_content_metadata_public'), table_name='product_digital_content')
    op.drop_index(op.f('ix_product_digital_content_metadata_private'), table_name='product_digital_content')
    op.drop_table('product_digital_content')
    op.drop_index('payment_pay_order_i_f22aa2_gin', table_name='payment')
    op.drop_index(op.f('ix_payment_psp_reference'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('order_line')
    op.drop_table('order_gift_card')
    op.drop_index(op.f('ix_order_fulfillment_order_id'), table_name='order_fulfillment')
    op.drop_index(op.f('ix_order_fulfillment_metadata_public'), table_name='order_fulfillment')
    op.drop_index(op.f('ix_order_fulfillment_metadata_private'), table_name='order_fulfillment')
    op.drop_table('order_fulfillment')
    op.drop_index(op.f('ix_order_event_app_id'), table_name='order_event')
    op.drop_table('order_event')
    op.drop_index('discount_or_name_d16858_gin', table_name='order_discount')
    op.drop_table('order_discount')
    op.drop_index(op.f('ix_menu_item_translation_menu_item_id'), table_name='menu_item_translation')
    op.drop_table('menu_item_translation')
    op.drop_index(op.f('ix_invoice_metadata_public'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_metadata_private'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('customer_event')
    op.drop_table('csv_export_event')
    op.drop_table('checkout_line')
    op.drop_table('checkout_gift_card')
    op.drop_table('assigned_variant_attribute')
    op.drop_index(op.f('ix_assigned_product_attribute_value_sort_order'), table_name='assigned_product_attribute_value')
    op.drop_table('assigned_product_attribute_value')
    op.drop_index(op.f('ix_assigned_page_attribute_value_sort_order'), table_name='assigned_page_attribute_value')
    op.drop_table('assigned_page_attribute_value')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_webhook_event_event_type'), table_name='webhook_event')
    op.drop_table('webhook_event')
    op.drop_table('warehouse_shipping_zone')
    op.drop_table('user_address_map')
    op.drop_table('site_setting_translation')
    op.drop_table('shipping_method_translation')
    op.drop_table('shipping_method_postal_code_rule')
    op.drop_table('shipping_method_excluded_product')
    op.drop_table('shipping_method_channel_listing')
    op.drop_index(op.f('ix_product_variant_sort_order'), table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_metadata_public'), table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_metadata_private'), table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_table('product_translation')
    op.drop_index(op.f('ix_product_media_sort_order'), table_name='product_media')
    op.drop_table('product_media')
    op.drop_index(op.f('ix_product_channel_listing_publication_date'), table_name='product_channel_listing')
    op.drop_table('product_channel_listing')
    op.drop_table('page_translation')
    op.drop_index(op.f('ix_order_user_email'), table_name='order')
    op.drop_index(op.f('ix_order_metadata_public'), table_name='order')
    op.drop_index(op.f('ix_order_metadata_private'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_menu_item_tree_id'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_sort_order'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_metadata_public'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_metadata_private'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_table('gift_card')
    op.drop_index(op.f('ix_discount_voucher_product_voucher_id'), table_name='discount_voucher_product')
    op.drop_index(op.f('ix_discount_voucher_product_product_id'), table_name='discount_voucher_product')
    op.drop_table('discount_voucher_product')
    op.drop_table('discount_sale_product')
    op.drop_index(op.f('ix_customer_note_date'), table_name='customer_note')
    op.drop_table('customer_note')
    op.drop_index(op.f('ix_csv_export_file_app_id'), table_name='csv_export_file')
    op.drop_table('csv_export_file')
    op.drop_index(op.f('ix_collection_product_sort_order'), table_name='collection_product')
    op.drop_table('collection_product')
    op.drop_index(op.f('ix_checkout_metadata_public'), table_name='checkout')
    op.drop_index(op.f('ix_checkout_metadata_private'), table_name='checkout')
    op.drop_table('checkout')
    op.drop_table('attribute_value_translation')
    op.drop_table('assigned_product_attribute')
    op.drop_table('assigned_page_attribute')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_warehouse_metadata_public'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_metadata_private'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_user_metadata_public'), table_name='user')
    op.drop_index(op.f('ix_user_metadata_private'), table_name='user')
    op.drop_index('account_username_email', table_name='user')
    op.drop_table('user')
    op.drop_table('staff_notification_recipient')
    op.drop_index(op.f('ix_site_setting_top_menu_id'), table_name='site_setting')
    op.drop_index(op.f('ix_site_setting_bottom_menu_id'), table_name='site_setting')
    op.drop_table('site_setting')
    op.drop_table('shipping_zone_channel')
    op.drop_index(op.f('ix_shipping_method_metadata_public'), table_name='shipping_method')
    op.drop_index(op.f('ix_shipping_method_metadata_private'), table_name='shipping_method')
    op.drop_table('shipping_method')
    op.drop_table('product_collection_translation')
    op.drop_table('product_collection_channel_listing')
    op.drop_table('product_category_translation')
    op.drop_index(op.f('ix_product_search_vector'), table_name='product')
    op.drop_index(op.f('ix_product_metadata_public'), table_name='product')
    op.drop_index(op.f('ix_product_metadata_private'), table_name='product')
    op.drop_table('product')
    op.drop_table('plugin_configuration')
    op.drop_index('page_title_slug', table_name='page')
    op.drop_index(op.f('ix_page_metadata_public'), table_name='page')
    op.drop_index(op.f('ix_page_metadata_private'), table_name='page')
    op.drop_table('page')
    op.drop_table('discount_voucher_translation')
    op.drop_table('discount_voucher_customer')
    op.drop_table('discount_voucher_collection')
    op.drop_table('discount_voucher_channel_listing')
    op.drop_table('discount_voucher_category')
    op.drop_index(op.f('ix_discount_sale_translation_sale_id'), table_name='discount_sale_translation')
    op.drop_table('discount_sale_translation')
    op.drop_table('discount_sale_collection')
    op.drop_index(op.f('ix_discount_sale_channel_listing_sale_id'), table_name='discount_sale_channel_listing')
    op.drop_index(op.f('ix_discount_sale_channel_listing_channel_id'), table_name='discount_sale_channel_listing')
    op.drop_table('discount_sale_channel_listing')
    op.drop_table('discount_sale_category')
    op.drop_index(op.f('ix_attribute_variant_sort_order'), table_name='attribute_variant')
    op.drop_table('attribute_variant')
    op.drop_index(op.f('ix_attribute_value_sort_order'), table_name='attribute_value')
    op.drop_index(op.f('ix_attribute_value_slug'), table_name='attribute_value')
    op.drop_index('idx_attribute_value_name_slug', table_name='attribute_value')
    op.drop_table('attribute_value')
    op.drop_index(op.f('ix_attribute_translation_attribute_id'), table_name='attribute_translation')
    op.drop_table('attribute_translation')
    op.drop_index(op.f('ix_attribute_product_sort_order'), table_name='attribute_product')
    op.drop_table('attribute_product')
    op.drop_index(op.f('ix_attribute_page_sort_order'), table_name='attribute_page')
    op.drop_table('attribute_page')
    op.drop_table('app_token')
    op.drop_table('app_permission')
    op.drop_index(op.f('ix_app_installation_permissions_app_installation_id'), table_name='app_installation_permissions')
    op.drop_table('app_installation_permissions')
    op.drop_table('staff')
    op.drop_index(op.f('ix_shipping_zone_metadata_public'), table_name='shipping_zone')
    op.drop_index(op.f('ix_shipping_zone_metadata_private'), table_name='shipping_zone')
    op.drop_table('shipping_zone')
    op.drop_index(op.f('ix_product_type_metadata_public'), table_name='product_type')
    op.drop_index(op.f('ix_product_type_metadata_private'), table_name='product_type')
    op.drop_table('product_type')
    op.drop_index(op.f('ix_product_collection_metadata_public'), table_name='product_collection')
    op.drop_index(op.f('ix_product_collection_metadata_private'), table_name='product_collection')
    op.drop_table('product_collection')
    op.drop_index(op.f('ix_product_category_tree_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_metadata_public'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_metadata_private'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_table('permission')
    op.drop_index('page_type_name_slug', table_name='page_type')
    op.drop_index(op.f('ix_page_type_metadata_public'), table_name='page_type')
    op.drop_index(op.f('ix_page_type_metadata_private'), table_name='page_type')
    op.drop_table('page_type')
    op.drop_index(op.f('ix_menu_metadata_public'), table_name='menu')
    op.drop_index(op.f('ix_menu_metadata_private'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_django_prices_vatlayer_vat_country_code'), table_name='django_prices_vatlayer_vat')
    op.drop_table('django_prices_vatlayer_vat')
    op.drop_table('django_prices_vatlayer_ratetypes')
    op.drop_table('django_prices_openexchangerates_conversionrate')
    op.drop_table('discount_voucher')
    op.drop_table('discount_sale')
    op.drop_table('channel')
    op.drop_index(op.f('ix_attribute_metadata_public'), table_name='attribute')
    op.drop_index(op.f('ix_attribute_metadata_private'), table_name='attribute')
    op.drop_table('attribute')
    op.drop_table('app_installation')
    op.drop_index(op.f('ix_app_metadata_public'), table_name='app')
    op.drop_index(op.f('ix_app_metadata_private'), table_name='app')
    op.drop_table('app')
    op.drop_table('address')
    # ### end Alembic commands ###
