"""empty message

Revision ID: 2e25022bfe68
Revises: d5b1cfb6f98b
Create Date: 2021-08-03 17:41:43.093231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e25022bfe68'
down_revision = 'd5b1cfb6f98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('order', 'created')
    op.add_column('order_discount', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_discount', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('order_fulfillment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_fulfillment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('order_fulfillment', 'created')
    op.add_column('order_fulfillment_line', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_fulfillment_line', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('order_line', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_line', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_line', 'updated_at')
    op.drop_column('order_line', 'created_at')
    op.drop_column('order_fulfillment_line', 'updated_at')
    op.drop_column('order_fulfillment_line', 'created_at')
    op.add_column('order_fulfillment', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('order_fulfillment', 'updated_at')
    op.drop_column('order_fulfillment', 'created_at')
    op.drop_column('order_discount', 'updated_at')
    op.drop_column('order_discount', 'created_at')
    op.add_column('order', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    # ### end Alembic commands ###
