"""empty message

Revision ID: 423f73fe755f
Revises: 2e25022bfe68
Create Date: 2021-08-16 21:15:17.527307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423f73fe755f'
down_revision = '2e25022bfe68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password_hash')
    # ### end Alembic commands ###
