"""empty message

Revision ID: 50843267c778
Revises: 062cfe148a4f
Create Date: 2021-08-24 13:44:33.731499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50843267c778'
down_revision = '062cfe148a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
