"""empty message

Revision ID: 9461c8fdc50e
Revises: 4eb0e8ce3f2d
Create Date: 2021-07-19 22:42:25.352910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9461c8fdc50e'
down_revision = '4eb0e8ce3f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_organization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_attr',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ENABLE', 'DISABLE', name='status'), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_attr_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('attr_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['product_attr.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_spu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('market_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_brand.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('market_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_spu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sku_stock',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_spu_sku_attr_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('spu_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('attr_id', sa.BigInteger(), nullable=True),
    sa.Column('attr_value_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['product_attr.id'], ),
    sa.ForeignKeyConstraint(['attr_value_id'], ['product_attr_value.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_sku.id'], ),
    sa.ForeignKeyConstraint(['spu_id'], ['product_spu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sys_organizations')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'updated_at')
    op.drop_column('sys_dept', 'created_at')
    op.drop_column('sys_dept', 'updated_at')
    op.drop_column('sys_permission', 'created_at')
    op.drop_column('sys_permission', 'updated_at')
    op.drop_column('sys_role', 'created_at')
    op.drop_column('sys_role', 'updated_at')
    op.drop_column('sys_user', 'created_at')
    op.drop_column('sys_user', 'updated_at')
    op.drop_column('sys_user_audit', 'created_at')
    op.drop_column('sys_user_audit', 'object_id')
    op.drop_column('sys_user_audit', 'updated_at')
    op.drop_column('sys_user_audit', 'object_type')
    op.drop_column('sys_user_role', 'created_at')
    op.drop_column('sys_user_role', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user_role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user_role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user_audit', sa.Column('object_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sys_user_audit', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user_audit', sa.Column('object_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('sys_user_audit', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_permission', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_permission', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_dept', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_dept', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('sys_organizations',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_organizations_pkey')
    )
    op.drop_table('product_spu_sku_attr_map')
    op.drop_table('product_sku_stock')
    op.drop_table('product_sku')
    op.drop_table('product_spu')
    op.drop_table('product_attr_value')
    op.drop_table('product_category')
    op.drop_table('product_brand')
    op.drop_table('product_attr')
    op.drop_table('sys_organization')
    op.drop_table('merchant')
    # ### end Alembic commands ###
