"""empty message

Revision ID: d5b1cfb6f98b
Revises: 19d5fbd43af3
Create Date: 2021-08-03 15:28:49.453003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b1cfb6f98b'
down_revision = '19d5fbd43af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('collection_product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_product_default_variant_id', 'product', 'product_variant', ['default_variant_id'], ['id'], use_alter=True)
    op.add_column('product_digital_content', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_digital_content', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_translation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_translation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_type', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_type', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_variant', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_variant', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_variant_translation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_variant_translation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variant_translation', 'updated_at')
    op.drop_column('product_variant_translation', 'created_at')
    op.drop_column('product_variant', 'updated_at')
    op.drop_column('product_variant', 'created_at')
    op.drop_column('product_type', 'updated_at')
    op.drop_column('product_type', 'created_at')
    op.drop_column('product_translation', 'updated_at')
    op.drop_column('product_translation', 'created_at')
    op.drop_column('product_digital_content', 'updated_at')
    op.drop_column('product_digital_content', 'created_at')
    op.drop_constraint('fk_product_default_variant_id', 'product', type_='foreignkey')
    op.drop_column('product', 'created_at')
    op.drop_column('collection_product', 'updated_at')
    op.drop_column('collection_product', 'created_at')
    # ### end Alembic commands ###
