"""
product(...): Product
productAttributeAssign(...): ProductAttributeAssign
productAttributeUnassign(...): ProductAttributeUnassign
productBulkDelete(...): ProductBulkDelete
productChannelListingUpdate(...): ProductChannelListingUpdate
productCreate(...): ProductCreate
productDelete(...): ProductDelete
productMediaBulkDelete(...): ProductMediaBulkDelete
productMediaCreate(...): ProductMediaCreate
productMediaDelete(...): ProductMediaDelete
productMediaReorder(...): ProductMediaReorder
productMediaUpdate(...): ProductMediaUpdate
productReorderAttributeValues(...): ProductReorderAttributeValues
productTranslate(...): ProductTranslate
productType(...): ProductType
productTypeBulkDelete(...): ProductTypeBulkDelete
productTypeCreate(...): ProductTypeCreate
productTypeDelete(...): ProductTypeDelete
productTypeReorderAttributes(...): ProductTypeReorderAttributes
productTypeUpdate(...): ProductTypeUpdate
productTypes(...): ProductTypeCountableConnection
productUpdate(...): ProductUpdate
productVariant(...): ProductVariant
productVariantBulkCreate(...): ProductVariantBulkCreate
productVariantBulkDelete(...): ProductVariantBulkDelete
productVariantChannelListingUpdate(...): ProductVariantChannelListingUpdate
productVariantCreate(...): ProductVariantCreate
productVariantDelete(...): ProductVariantDelete
productVariantReorder(...): ProductVariantReorder
productVariantReorderAttributeValues(...): ProductVariantReorderAttributeValues
productVariantSetDefault(...): ProductVariantSetDefault
productVariantStocksCreate(...): ProductVariantStocksCreate
productVariantStocksDelete(...): ProductVariantStocksDelete
productVariantStocksUpdate(...): ProductVariantStocksUpdate
productVariantTranslate(...): ProductVariantTranslate
productVariantUpdate(...): ProductVariantUpdate
productVariants(...): ProductVariantCountableConnection
products(...): ProductCountableConnection
"""
