# Generated by Django 4.2.3 on 2023-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SdImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_image",
            },
        ),
        migrations.CreateModel(
            name="SdModelCheckpoint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_model_checkpoint",
            },
        ),
        migrations.CreateModel(
            name="SdModelLora",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_model_lora",
            },
        ),
        migrations.CreateModel(
            name="SdModelVae",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_model_vae",
            },
        ),
        migrations.CreateModel(
            name="SdPrompt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("checkpoint", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("n_prompt", models.TextField()),
                ("sampler", models.CharField(max_length=50)),
                ("cfg_scale", models.IntegerField(default=7)),
                ("steps", models.IntegerField(default=30)),
                ("seed", models.BigIntegerField(default=-1)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_prompt",
            },
        ),
        migrations.CreateModel(
            name="SdPromptTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_zh", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_prompt_tag",
            },
        ),
        migrations.CreateModel(
            name="SdSpellTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("checkpoint", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("n_prompt", models.TextField()),
                ("sampler", models.CharField(max_length=50)),
                ("cfg_scale", models.IntegerField(default=7)),
                ("steps", models.IntegerField(default=30)),
                ("seed", models.BigIntegerField(default=-1)),
                ("sort_num", models.IntegerField(db_index=True, default=999)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sd_spell_template",
            },
        ),
    ]
