# Generated by Django 4.2.3 on 2023-08-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tifa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdprompt",
            name="slug",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdspelltemplate",
            name="slug",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
