# Generated by Django 4.2.3 on 2023-08-02 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tifa", "0002_sdprompt_slug_sdspelltemplate_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sdprompt",
            old_name="slug",
            new_name="template_slug",
        ),
    ]
