"""Added account table

Revision ID: 045d17360ab6
Revises: 4db8fd5ffbe5
Create Date: 2020-04-16 13:25:38.549105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045d17360ab6'
down_revision = '4db8fd5ffbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
