"""empty message

Revision ID: 4db8fd5ffbe5
Revises: af333d6b14bf
Create Date: 2020-04-16 12:43:41.421580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db8fd5ffbe5'
down_revision = 'af333d6b14bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
