"""empty message

Revision ID: 64039c7832cf
Revises: 98e5cbbb93e9
Create Date: 2020-04-16 20:39:11.226361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64039c7832cf'
down_revision = '98e5cbbb93e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('not_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'not_superuser')
    # ### end Alembic commands ###
