"""empty message

Revision ID: af333d6b14bf
Revises: f136f79564f2
Create Date: 2020-04-16 12:32:46.508668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af333d6b14bf'
down_revision = 'f136f79564f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
