"""empty message

Revision ID: e9c39c6aedca
Revises: 045d17360ab6
Create Date: 2020-04-16 20:14:35.665229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c39c6aedca'
down_revision = '045d17360ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
