"""
order(...): Order
orderAddNote(...): OrderAddNote
orderBulkCancel(...): OrderBulkCancel
orderByToken(...): Order
orderCancel(...): OrderCancel
orderCapture(...): OrderCapture
orderConfirm(...): OrderConfirm
orderDiscountAdd(...): OrderDiscountAdd
orderDiscountDelete(...): OrderDiscountDelete
orderDiscountUpdate(...): OrderDiscountUpdate
orderFulfill(...): OrderFulfill
orderFulfillmentCancel(...): FulfillmentCancel
orderFulfillmentRefundProducts(...): FulfillmentRefundProducts
orderFulfillmentReturnProducts(...): FulfillmentReturnProducts
orderFulfillmentUpdateTracking(...): FulfillmentUpdateTracking
orderLineDelete(...): OrderLineDelete
orderLineDiscountRemove(...): OrderLineDiscountRemove
orderLineDiscountUpdate(...): OrderLineDiscountUpdate
orderLineUpdate(...): OrderLineUpdate
orderLinesCreate(...): OrderLinesCreate
orderMarkAsPaid(...): OrderMarkAsPaid
orderRefund(...): OrderRefund
orderSettings: OrderSettings
orderSettingsUpdate(...): OrderSettingsUpdate
orderUpdate(...): OrderUpdate
orderUpdateShipping(...): OrderUpdateShipping
orderVoid(...): OrderVoid
orders(...): OrderCountableConnection
ordersTotal(...): TaxedMoney
"""
