name: run-pytest-when-push
on: push
jobs:
  build_with_ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: docker pull ghcr.io/$GITHUB_REPOSITORY/tifa:local || true
      - run: docker build . -t 'tifa:local' -f 'compose/app/Dockerfile' . --cache-from=ghcr.io/$GITHUB_REPOSITORY/tifa:local
      - run: docker tag 'tifa:local' ghcr.io/$GITHUB_REPOSITORY/tifa:local && docker push ghcr.io/$GITHUB_REPOSITORY/tifa:local || true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build elasticsearch docker image
        run: make build-elasticsearch
      - name: Build tifa docker image
        run: make build-tifa
      - name: Just up the stack
        run: docker-compose up -d
      - name: Run Pytest
        run: make test

