name: run-pytest-when-push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # In this step, this action saves a list of existing images,
        # the cache is created without them in the post run.
        # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build elasticsearch docker image
        run: make build-elasticsearch
      - name: Build tifa docker image
        run: make build-tifa
      - name: Just up the stack
        run: docker-compose up -d
      - name: Run Pytest
        run: make test

